from django.db import models

class products(models.Model):
    product_code=models.CharField(max_length=255,unique=False)
    product_name=models.CharField(max_length=255,null=False)
    product_description=models.TextField(max_length=2000,blank=True,null=True)
    vendor_Id = models.CharField(max_length=255,null=True)
    vendor_name=models.CharField(max_length=255,blank=True,null=True)
    category=models.CharField(max_length=255,blank=True,null=True)
    sub_category=models.CharField(max_length=255,blank=True,null=True)
    image=models.ImageField(null=True)
    retail_price=models.FloatField(null=True)
    cost_price=models.FloatField(null=True)
    uom=models.CharField(max_length=255,blank=True,null=True)
    uom_values=models.CharField(max_length=255,blank=True,null=True)
    addidtional_details=models.TextField(null=True)
    product_group=models.CharField(max_length=255,null=True)
    quantity=models.IntegerField(null=True,blank=True)
    state_manager = models.DateTimeField(blank=True, null=True)
    created_time = models.DateTimeField(blank=True, null=True)
    updated_time = models.DateTimeField(blank=True, null=True)
    file_upload = models.CharField(max_length=10000,null=True,blank=True)
    HSN = models.CharField(max_length=255,null=True)
    SAC = models.CharField(max_length=255,null=True)
    dealer_price = models.FloatField(null=True)
    last_purchase_price = models.FloatField(null=True)
    is_inventory = models.BooleanField(default=False,null=True)
    is_tax_included = models.BooleanField(default=False,null=True)
    is_billable = models.BooleanField(default=False,null=True)
    is_service = models.BooleanField(default=False,null=True)
    is_sample = models.BooleanField(default=False,null=True)
    is_active = models.BooleanField(default=False,null=True)

class product_file(models.Model):
    files = models.FileField(upload_to="")
    product_code = models.CharField(max_length=255)
